[2024-04-24T18:04:58.577+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-24T18:04:58.591+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monthly_report.transform manual__2024-04-24T18:01:30.902223+00:00 [queued]>
[2024-04-24T18:04:58.596+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monthly_report.transform manual__2024-04-24T18:01:30.902223+00:00 [queued]>
[2024-04-24T18:04:58.597+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-24T18:04:58.606+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): transform> on 2024-04-24 18:01:30.902223+00:00
[2024-04-24T18:04:58.611+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=167) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-24T18:04:58.612+0000] {standard_task_runner.py:63} INFO - Started process 169 to run task
[2024-04-24T18:04:58.612+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'monthly_report', 'transform', 'manual__2024-04-24T18:01:30.902223+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/homework2.py', '--cfg-path', '/tmp/tmpwsr6szw5']
[2024-04-24T18:04:58.613+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask transform
[2024-04-24T18:04:58.644+0000] {task_command.py:426} INFO - Running <TaskInstance: monthly_report.transform manual__2024-04-24T18:01:30.902223+00:00 [running]> on host bdc10b020525
[2024-04-24T18:04:58.698+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='monthly_report' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-04-24T18:01:30.902223+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-24T18:01:30.902223+00:00'
[2024-04-24T18:04:58.699+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-24T18:05:01.676+0000] {logging_mixin.py:188} WARNING -   0%|          | 0/10 [00:00<?, ?it/s]
[2024-04-24T18:05:03.017+0000] {logging_mixin.py:188} WARNING -  10%|#         | 1/10 [00:01<00:12,  1.34s/it]
[2024-04-24T18:05:04.472+0000] {logging_mixin.py:188} WARNING -  20%|##        | 2/10 [00:02<00:11,  1.41s/it]
[2024-04-24T18:05:05.713+0000] {logging_mixin.py:188} WARNING -  30%|###       | 3/10 [00:04<00:09,  1.33s/it]
[2024-04-24T18:05:07.422+0000] {logging_mixin.py:188} WARNING -  40%|####      | 4/10 [00:05<00:08,  1.48s/it]
[2024-04-24T18:05:09.113+0000] {logging_mixin.py:188} WARNING -  50%|#####     | 5/10 [00:07<00:07,  1.56s/it]
[2024-04-24T18:05:10.325+0000] {logging_mixin.py:188} WARNING -  60%|######    | 6/10 [00:08<00:05,  1.44s/it]
[2024-04-24T18:05:11.933+0000] {logging_mixin.py:188} WARNING -  70%|#######   | 7/10 [00:10<00:04,  1.49s/it]
[2024-04-24T18:05:13.749+0000] {logging_mixin.py:188} WARNING -  80%|########  | 8/10 [00:12<00:03,  1.60s/it]
[2024-04-24T18:05:14.643+0000] {logging_mixin.py:188} WARNING -  90%|######### | 9/10 [00:12<00:01,  1.38s/it]
[2024-04-24T18:05:15.509+0000] {logging_mixin.py:188} WARNING - 100%|##########| 10/10 [00:13<00:00,  1.22s/it]
[2024-04-24T18:05:15.510+0000] {logging_mixin.py:188} WARNING - 100%|##########| 10/10 [00:13<00:00,  1.38s/it]
[2024-04-24T18:05:15.561+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-24T18:05:15.563+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/homework2.py", line 48, in transfrom
    df_tmp.to_csv('data/flags_activity.csv', mode = 'a',index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'data'
[2024-04-24T18:05:15.585+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=monthly_report, task_id=transform, execution_date=20240424T180130, start_date=20240424T180458, end_date=20240424T180515
[2024-04-24T18:05:15.603+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task transform (Cannot save file into a non-existent directory: 'data'; 169)
[2024-04-24T18:05:15.650+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-24T18:05:15.670+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-24T18:05:15.671+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
