[2025-05-04T23:20:58.990+0300] {processor.py:161} INFO - Started process (PID=19727) to work on /Users/admin/airflow/dags/.ipynb_checkpoints/etc_pipline-checkpoint.py
[2025-05-04T23:20:58.990+0300] {processor.py:830} INFO - Processing file /Users/admin/airflow/dags/.ipynb_checkpoints/etc_pipline-checkpoint.py for tasks to queue
[2025-05-04T23:20:58.991+0300] {logging_mixin.py:188} INFO - [2025-05-04T23:20:58.991+0300] {dagbag.py:540} INFO - Filling up the DagBag from /Users/admin/airflow/dags/.ipynb_checkpoints/etc_pipline-checkpoint.py
[2025-05-04T23:20:58.993+0300] {logging_mixin.py:188} INFO - [2025-05-04T23:20:58.992+0300] {dagbag.py:350} ERROR - Failed to import: /Users/admin/airflow/dags/.ipynb_checkpoints/etc_pipline-checkpoint.py
Traceback (most recent call last):
  File "/Users/admin/anaconda3/lib/python3.11/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/admin/airflow/dags/.ipynb_checkpoints/etc_pipline-checkpoint.py", line 5, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2025-05-04T23:20:58.993+0300] {processor.py:842} WARNING - No viable dags retrieved from /Users/admin/airflow/dags/.ipynb_checkpoints/etc_pipline-checkpoint.py
[2025-05-04T23:20:59.041+0300] {processor.py:183} INFO - Processing /Users/admin/airflow/dags/.ipynb_checkpoints/etc_pipline-checkpoint.py took 0.053 seconds
